version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: >
      --requirepass TestPassword8738

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/opt/lexicom/app
    depends_on:
      - redis
